language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.8
  - pypy
  - pypy3

os: linux

virtualenv:
  system_site_packages: true

install:
  - pip install -r dev_requirements.txt
  - pip install .

script:
  - bash ./build.sh
