language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.8
  - pypy
  - pypy3

os: linux

install:
  - pip install -e .
  - pip install -r dev_requirements.txt
  - python setup.py build install

script:
  - make
